   
(っ◔◡◔)っ ♥ ULTROIDOFFICIAL ♥
░╚════╝░░╚════╝░╚═════╝░╚══════╝
                                          
[06-Sep-25 08:53:57 - INFO] - aiohttp.access - 172.31.97.98 [06/Sep/2025:08:53:57 +0000] "GET / HTTP/1.1" 200 178 "https://2afc7d04-7d04-4379-9cd9-9c80382bddcd-00-3sw0k737hgeel.pike.replit.dev/__replco/workspace_iframe.html?initialPath=%2F&id=%3Ar23i%3A" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/139.0.0.0 Safari/537.36"
[06-Sep-25 08:53:58 - ERROR] - pyrogram.dispatcher - is_subscribed() takes 3 positional arguments but 4 were given
Traceback (most recent call last):
  File "/home/runner/workspace/.pythonlibs/lib/python3.11/site-packages/pyrogram/dispatcher.py", line 242, in handler_worker
    await self.loop.run_in_executor(
  File "/nix/store/7d088dip86hlzri9sk0h78b63yfmx0a0-python3-3.11.13/lib/python3.11/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/workspace/.pythonlibs/lib/python3.11/site-packages/pyrogram/sync.py", line 78, in async_to_sync_wrap
    return asyncio.run_coroutine_threadsafe(coroutine, main_loop).result()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/nix/store/7d088dip86hlzri9sk0h78b63yfmx0a0-python3-3.11.13/lib/python3.11/concurrent/futures/_base.py", line 456, in result
    return self.__get_result()
           ^^^^^^^^^^^^^^^^^^^
  File "/nix/store/7d088dip86hlzri9sk0h78b63yfmx0a0-python3-3.11.13/lib/python3.11/concurrent/futures/_base.py", line 401, in __get_result
    raise self._exception
  File "/home/runner/workspace/.pythonlibs/lib/python3.11/site-packages/pyromod/listen/message_handler.py", line 98, in resolve_future_or_callback
    await self.original_callback(client, message, *args)
  File "/home/runner/workspace/plugins/start.py", line 117, in start_handler
    if not await subscribed(filters, client, message):
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: is_subscribed() takes 3 positional arguments but 4 were given